apiVersion: v1
kind: ConfigMap
metadata:
  name: pubrush-config
data:
  DB_PORT: "5432"
  DB_NAME: "pubrush"
  DB_USER: "pubrush"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_FROM: "noreply@pubrush.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: pubrush-secrets
type: Opaque
stringData:
  DB_PASSWORD: "k8M2pAzW9xF5yR7qL3sT9vB4"
  SMTP_PASSWORD: "gplx ylkn rmeb zked"
  SMTP_USER: "pubrush.app@gmail.com"
