apiVersion: v1
kind: ConfigMap
metadata:
  name: pubrush-config
data:
  DB_PORT: "5432"
  DB_NAME: "pubrush"
  DB_USER: "pubrush"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_FROM: "noreply@pubrush.com"

