import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F6FA',
  },
  map: {
    flex: 1,
  },
  topBarWrapper: {
    position: 'absolute',
    top: 65,
    left: 16,
    right: 16,
  },
  topBar: {
    minHeight: 74,
    borderRadius: 24,
    paddingLeft: 18,
    paddingRight: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  brandBlock: {
    flex: 1,
    paddingRight: 12,
  },
  brand: {
    fontSize: 24,
    fontWeight: '800',
    color: '#111827',
    letterSpacing: -0.8,
  },
  brandSubtitle: {
    marginTop: 2,
    fontSize: 14,
    color: 'rgba(75,85,99,0.92)',
  },
  menuButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(17,24,39,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuButtonIcon: {
    color: '#FFFFFF',
    fontSize: 21,
    fontWeight: '700',
    marginTop: -1,
  },

locationControlWrapper: {
  position: 'absolute',
  right: 10,
  bottom: 50,
},
locationControlShell: {
  width: 50,
  height: 50,
  borderRadius: 22,
  backgroundColor: 'rgba(255,255,255,0.58)',
  borderWidth: 1,
  borderColor: 'rgba(255,255,255,0.65)',
  alignItems: 'center',
  justifyContent: 'center',
  shadowColor: '#000',
  shadowOpacity: 0.08,
  shadowRadius: 18,
  shadowOffset: { width: 0, height: 8 },
  elevation: 4,
},
locationControlButton: {
  width: 46,
  height: 46,
  borderRadius: 16,
  backgroundColor: 'rgba(255,255,255,0.92)',
  alignItems: 'center',
  justifyContent: 'center',
},
locationControlButtonDisabled: {
  opacity: 0,
},

  modalRoot: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(17,24,39,0.28)',
  },
  menuPanel: {
    width: 310,
    backgroundColor: '#F3F4F6', // Light gray background like iOS Grouped Settings
    borderTopLeftRadius: 28,
    borderBottomLeftRadius: 28,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: -4, height: 0 },
    elevation: 10,
  },
  menuHeader: {
    marginBottom: 8,
  },
  menuTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#111827',
    letterSpacing: -1,
  },
  menuSubtitle: {
    marginTop: 4,
    fontSize: 14,
    color: '#6B7280',
  },
  sectionHeader: {
    fontSize: 12,
    fontWeight: '800',
    color: '#8E8E93',
    letterSpacing: 1,
    marginBottom: 8,
    marginLeft: 4,
  },
  profileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#6366F1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  profileTextWrapper: {
    flex: 1,
  },
  profileName: {
    fontSize: 17,
    fontWeight: '700',
    color: '#111827',
  },
  profileEmail: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  profileDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: 14,
  },
  statsContainer: {
    alignItems: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
  },
  statLabel: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 2,
    fontWeight: '500',
  },
  statVerticalDivider: {
    width: 1,
    height: 24,
    backgroundColor: '#E5E7EB',
  },
  gridSectionContainer: {
    marginTop: 24,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  gridCard: {
    width: '48%',
    borderRadius: 16,
    borderWidth: 1.5,
    padding: 14,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.02,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  gridCardFullWidth: {
    width: '100%',
    borderRadius: 16,
    borderWidth: 1.5,
    padding: 14,
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.02,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
    backgroundColor: '#FFF1F2',
    borderColor: '#FFE4E6',
  },
  gridIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  gridCardTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  gridCardSubtitle: {
    fontSize: 10,
    color: '#6B7280',
    marginTop: 2,
  },
  settingsSectionContainer: {
    marginTop: 12,
  },
  settingsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOpacity: 0.02,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
  },
  settingsRowText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    flex: 1,
  },
  settingsRowDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  loadingWrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
