import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F6FA',
  },
  map: {
    flex: 1,
  },
  topBarWrapper: {
    position: 'absolute',
    top: 65,
    left: 16,
    right: 16,
  },
  topBar: {
    minHeight: 74,
    borderRadius: 24,
    paddingLeft: 18,
    paddingRight: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.58)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  brandBlock: {
    flex: 1,
    paddingRight: 12,
  },
  brand: {
    fontSize: 24,
    fontWeight: '800',
    color: '#111827',
    letterSpacing: -0.8,
  },
  brandSubtitle: {
    marginTop: 2,
    fontSize: 14,
    color: 'rgba(75,85,99,0.92)',
  },
  menuButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(17,24,39,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuButtonIcon: {
    color: '#FFFFFF',
    fontSize: 21,
    fontWeight: '700',
    marginTop: -1,
  },

locationControlWrapper: {
  position: 'absolute',
  right: 10,
  bottom: 50,
},
locationControlShell: {
  width: 50,
  height: 50,
  borderRadius: 22,
  backgroundColor: 'rgba(255,255,255,0.58)',
  borderWidth: 1,
  borderColor: 'rgba(255,255,255,0.65)',
  alignItems: 'center',
  justifyContent: 'center',
  shadowColor: '#000',
  shadowOpacity: 0.08,
  shadowRadius: 18,
  shadowOffset: { width: 0, height: 8 },
  elevation: 4,
},
locationControlButton: {
  width: 46,
  height: 46,
  borderRadius: 16,
  backgroundColor: 'rgba(255,255,255,0.92)',
  alignItems: 'center',
  justifyContent: 'center',
},
locationControlButtonDisabled: {
  opacity: 0,
},

  modalRoot: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(17,24,39,0.28)',
  },
  menuPanel: {
    width: 310,
    backgroundColor: '#FFFFFF',
    paddingTop: 72,
    paddingHorizontal: 20,
    paddingBottom: 28,
    borderTopLeftRadius: 28,
    borderBottomLeftRadius: 28,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: -4, height: 0 },
    elevation: 10,
  },
  menuHeader: {
    marginBottom: 22,
  },
  menuTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#111827',
    letterSpacing: -1,
  },
  menuSubtitle: {
    marginTop: 4,
    fontSize: 14,
    color: '#6B7280',
  },
  menuItem: {
    backgroundColor: '#F8FAFC',
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  menuItemTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  menuItemSubtitle: {
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
  },
  logoutButton: {
    marginTop: 10,
    height: 50,
    borderRadius: 16,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
    loadingWrapper: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
});
