"""Add partner events and map filters

Revision ID: 01b4c5c4ebe0
Revises: 3db1b648caca
Create Date: 2026-06-08 16:29:36.449550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b4c5c4ebe0'
down_revision: Union[str, Sequence[str], None] = '3db1b648caca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('osm_query', sa.Text(), nullable=False),
    sa.Column('google_type', sa.String(length=100), nullable=True),
    sa.Column('is_global', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_filters_key'), 'map_filters', ['key'], unique=True)
    op.create_table('partner_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_events_code'), 'partner_events', ['code'], unique=True)
    op.create_table('event_map_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['partner_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_id'], ['map_filters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'filter_id', name='uq_event_map_filter')
    )
    op.create_index(op.f('ix_event_map_filters_event_id'), 'event_map_filters', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_map_filters_filter_id'), 'event_map_filters', ['filter_id'], unique=False)
    op.add_column('barathons', sa.Column('partner_event_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_barathons_partner_event_id'), 'barathons', ['partner_event_id'], unique=False)
    op.create_foreign_key(None, 'barathons', 'partner_events', ['partner_event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Custom changes: drop check constraints on stop_type from barathon_stops
    op.execute("ALTER TABLE barathon_stops DROP CONSTRAINT IF EXISTS chk_barathon_stops_type;")

    # Seed data
    op.execute("""
    INSERT INTO map_filters (key, label, icon, osm_query, google_type, is_global, created_at) VALUES
    ('bar', 'Bars', 'beer', 'nwr["amenity"~"^(pub|bar)$"]', 'bar', true, NOW()),
    ('food', 'Restaurants', 'restaurant', 'nwr["amenity"~"^(restaurant|fast_food|cafe)$"]', 'restaurant', true, NOW());
    """)

    op.execute("""
    INSERT INTO partner_events (name, code, description, is_active, created_at) VALUES
    ('Événement Partenaire', 'TOULOUSE2026', 'Un événement spécial avec des épreuves, des points de secours et des établissements partenaires.', true, NOW());
    """)

    op.execute("""
    INSERT INTO map_filters (key, label, icon, osm_query, google_type, is_global, created_at) VALUES
    ('first_aid', 'Secours', 'medical', 'nwr["amenity"~"^(first_aid|hospital)$"]', 'hospital', false, NOW()),
    ('challenge', 'Épreuves', 'flag', 'nwr["amenity"~"^(townhall|community_centre|monument)$"]', 'tourist_attraction', false, NOW()),
    ('partner_restaurant', 'Partenaires', 'pizza', 'nwr["amenity"="restaurant"]', 'restaurant', false, NOW());
    """)

    op.execute("""
    INSERT INTO event_map_filters (event_id, filter_id)
    SELECT pe.id, mf.id
    FROM partner_events pe, map_filters mf
    WHERE pe.code = 'TOULOUSE2026' AND mf.key IN ('first_aid', 'challenge', 'partner_restaurant');
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Custom changes: restore check constraints
    op.execute("ALTER TABLE barathon_stops ADD CONSTRAINT chk_barathon_stops_type CHECK (stop_type IN ('bar', 'food', 'meeting_point', 'other'));")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'barathons', type_='foreignkey')
    op.drop_index(op.f('ix_barathons_partner_event_id'), table_name='barathons')
    op.drop_column('barathons', 'partner_event_id')
    op.drop_index(op.f('ix_event_map_filters_filter_id'), table_name='event_map_filters')
    op.drop_index(op.f('ix_event_map_filters_event_id'), table_name='event_map_filters')
    op.drop_table('event_map_filters')
    op.drop_index(op.f('ix_partner_events_code'), table_name='partner_events')
    op.drop_table('partner_events')
    op.drop_index(op.f('ix_map_filters_key'), table_name='map_filters')
    op.drop_table('map_filters')
    # ### end Alembic commands ###
