"""Add saved barathons

Revision ID: 369131e2c95e
Revises: af1da7454ad2
Create Date: 2026-06-03 11:00:46.789486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369131e2c95e'
down_revision: Union[str, Sequence[str], None] = 'af1da7454ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_barathons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('travel_time_between_bars_minutes', sa.Integer(), nullable=False),
    sa.Column('max_time_in_bar_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_barathons_user_id'), 'saved_barathons', ['user_id'], unique=False)
    op.create_table('saved_barathon_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('saved_barathon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stop_type', sa.String(length=20), server_default='bar', nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['saved_barathon_id'], ['saved_barathons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_barathon_id', 'stop_order', name='uq_saved_barathon_stop_order')
    )
    op.create_index(op.f('ix_saved_barathon_stops_saved_barathon_id'), 'saved_barathon_stops', ['saved_barathon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_barathon_stops_saved_barathon_id'), table_name='saved_barathon_stops')
    op.drop_table('saved_barathon_stops')
    op.drop_index(op.f('ix_saved_barathons_user_id'), table_name='saved_barathons')
    op.drop_table('saved_barathons')
    # ### end Alembic commands ###
