"""Add is_refund to barathon expenses

Revision ID: 3db1b648caca
Revises: 369131e2c95e
Create Date: 2026-06-03 11:22:35.767896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db1b648caca'
down_revision: Union[str, Sequence[str], None] = '369131e2c95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barathon_expenses', sa.Column('is_refund', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barathon_expenses', 'is_refund')
    # ### end Alembic commands ###
