"""add_user_created_at_and_app_usage_logs

Revision ID: 4541c061ea47
Revises: 7ddc035a4832
Create Date: 2026-06-09 16:06:02.698077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4541c061ea47'
down_revision: Union[str, Sequence[str], None] = '7ddc035a4832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_usage_logs_user_id'), 'app_usage_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

    # Seed dummy users with spread created_at timestamps over 6 months
    op.execute("""
    INSERT INTO users (email, username, password_hash, is_admin, created_at) VALUES
    ('thomas.t@example.com', 'thomas_t', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '1 day'),
    ('sophie.s@example.com', 'sophie_s', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '3 days'),
    ('pierre.p@example.com', 'pierre_p', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '7 days'),
    ('marie.m@example.com', 'marie_m', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '12 days'),
    ('luc.l@example.com', 'luc_l', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '20 days'),
    ('emma.e@example.com', 'emma_e', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '35 days'),
    ('hugo.h@example.com', 'hugo_h', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '50 days'),
    ('chloe.c@example.com', 'chloe_c', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '70 days'),
    ('nicolas.n@example.com', 'nicolas_n', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '95 days'),
    ('julie.j@example.com', 'julie_j', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '130 days'),
    ('antoine.a@example.com', 'antoine_a', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '160 days'),
    ('lea.l@example.com', 'lea_l', '$2b$12$K1dJv/bI.GzT56Q8Uv9H9.gYv9m9K9j9...', false, NOW() - INTERVAL '200 days')
    ON CONFLICT (email) DO NOTHING;
    """)

    # Seed app usage logs (logins and usages) spread over the last 30 days
    op.execute("""
    INSERT INTO app_usage_logs (user_id, action, created_at)
    SELECT u.id, 'login', NOW() - (val || ' hours')::INTERVAL
    FROM users u, generate_series(1, 120) val
    WHERE u.email LIKE '%@example.com' AND val % 3 = 0;
    """)
    op.execute("""
    INSERT INTO app_usage_logs (user_id, action, created_at)
    SELECT u.id, 'use_app', NOW() - (val || ' hours')::INTERVAL
    FROM users u, generate_series(1, 120) val
    WHERE u.email LIKE '%@example.com' AND val % 2 = 0;
    """)

    # Seed partner event registrations for TOULOUSE2026
    op.execute("""
    INSERT INTO partner_event_users (event_id, user_id, joined_at)
    SELECT pe.id, u.id, NOW() - (val || ' days')::INTERVAL
    FROM partner_events pe, users u, generate_series(1, 8) val
    WHERE pe.code = 'TOULOUSE2026'
      AND u.email IN ('thomas.t@example.com', 'sophie.s@example.com', 'pierre.p@example.com', 'marie.m@example.com', 'luc.l@example.com', 'emma.e@example.com', 'hugo.h@example.com', 'chloe.c@example.com')
      AND u.email LIKE '%' || (CASE val WHEN 1 THEN 'thomas.t' WHEN 2 THEN 'sophie.s' WHEN 3 THEN 'pierre.p' WHEN 4 THEN 'marie.m' WHEN 5 THEN 'luc.l' WHEN 6 THEN 'emma.e' WHEN 7 THEN 'hugo.h' ELSE 'chloe.c' END) || '%'
    ON CONFLICT (event_id, user_id) DO NOTHING;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('ix_app_usage_logs_user_id'), table_name='app_usage_logs')
    op.drop_table('app_usage_logs')
    # ### end Alembic commands ###
