"""add completion fields to barathon stops

Revision ID: 46652bb8f5c9
Revises: cd06f254cf8b
Create Date: 2026-04-02 16:52:36.239293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46652bb8f5c9'
down_revision: Union[str, Sequence[str], None] = 'cd06f254cf8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barathon_stops', sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('barathon_stops', sa.Column('entered_at', sa.DateTime(), nullable=True))
    op.add_column('barathon_stops', sa.Column('left_at', sa.DateTime(), nullable=True))
    op.add_column('barathon_stops', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barathon_stops', 'completed_at')
    op.drop_column('barathon_stops', 'left_at')
    op.drop_column('barathon_stops', 'entered_at')
    op.drop_column('barathon_stops', 'is_completed')
    # ### end Alembic commands ###
