"""add_partner_event_dates_and_tickets

Revision ID: 685a70091b4a
Revises: 01b4c5c4ebe0
Create Date: 2026-06-09 14:19:59.409641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685a70091b4a'
down_revision: Union[str, Sequence[str], None] = '01b4c5c4ebe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=100), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['partner_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_tickets_event_id'), 'event_tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_tickets_ticket_code'), 'event_tickets', ['ticket_code'], unique=True)
    op.create_index(op.f('ix_event_tickets_used_by_user_id'), 'event_tickets', ['used_by_user_id'], unique=False)
    op.create_table('partner_event_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['partner_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_partner_event_user')
    )
    op.create_index(op.f('ix_partner_event_users_event_id'), 'partner_event_users', ['event_id'], unique=False)
    op.create_index(op.f('ix_partner_event_users_user_id'), 'partner_event_users', ['user_id'], unique=False)
    op.add_column('partner_events', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('partner_events', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('partner_events', sa.Column('requires_ticket', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_events', 'requires_ticket')
    op.drop_column('partner_events', 'end_date')
    op.drop_column('partner_events', 'start_date')
    op.drop_index(op.f('ix_partner_event_users_user_id'), table_name='partner_event_users')
    op.drop_index(op.f('ix_partner_event_users_event_id'), table_name='partner_event_users')
    op.drop_table('partner_event_users')
    op.drop_index(op.f('ix_event_tickets_used_by_user_id'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_ticket_code'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_event_id'), table_name='event_tickets')
    op.drop_table('event_tickets')
    # ### end Alembic commands ###
