"""add_partner_event_spots

Revision ID: 7ddc035a4832
Revises: 685a70091b4a
Create Date: 2026-06-09 15:03:49.278417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ddc035a4832'
down_revision: Union[str, Sequence[str], None] = '685a70091b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_event_spots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spot_type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='chk_partner_event_spots_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='chk_partner_event_spots_longitude'),
    sa.ForeignKeyConstraint(['event_id'], ['partner_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_event_spots_event_id'), 'partner_event_spots', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_event_spots_event_id'), table_name='partner_event_spots')
    op.drop_table('partner_event_spots')
    # ### end Alembic commands ###
