"""add roles and barathon participant roles

Revision ID: a64abd556f76
Revises: a234f451c325
Create Date: 2026-04-02 15:26:40.707899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64abd556f76'
down_revision: Union[str, Sequence[str], None] = 'a234f451c325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('barathon_participant_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barathon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barathon_id'], ['barathons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barathon_id', 'role_id', name='uq_barathon_role_unique'),
    sa.UniqueConstraint('barathon_id', 'user_id', name='uq_barathon_role_user')
    )
    op.create_index(op.f('ix_barathon_participant_roles_barathon_id'), 'barathon_participant_roles', ['barathon_id'], unique=False)
    op.create_index(op.f('ix_barathon_participant_roles_role_id'), 'barathon_participant_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_barathon_participant_roles_user_id'), 'barathon_participant_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barathon_participant_roles_user_id'), table_name='barathon_participant_roles')
    op.drop_index(op.f('ix_barathon_participant_roles_role_id'), table_name='barathon_participant_roles')
    op.drop_index(op.f('ix_barathon_participant_roles_barathon_id'), table_name='barathon_participant_roles')
    op.drop_table('barathon_participant_roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
