"""add_barathon_expenses

Revision ID: af1da7454ad2
Revises: 530714b1212d
Create Date: 2026-06-01 10:44:27.196706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1da7454ad2'
down_revision: Union[str, Sequence[str], None] = '530714b1212d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barathon_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barathon_id', sa.Integer(), nullable=False),
    sa.Column('payer_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['barathon_id'], ['barathons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barathon_expenses_barathon_id'), 'barathon_expenses', ['barathon_id'], unique=False)
    op.create_index(op.f('ix_barathon_expenses_payer_user_id'), 'barathon_expenses', ['payer_user_id'], unique=False)
    op.create_table('barathon_expense_beneficiaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['barathon_expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barathon_expense_beneficiaries_expense_id'), 'barathon_expense_beneficiaries', ['expense_id'], unique=False)
    op.create_index(op.f('ix_barathon_expense_beneficiaries_user_id'), 'barathon_expense_beneficiaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barathon_expense_beneficiaries_user_id'), table_name='barathon_expense_beneficiaries')
    op.drop_index(op.f('ix_barathon_expense_beneficiaries_expense_id'), table_name='barathon_expense_beneficiaries')
    op.drop_table('barathon_expense_beneficiaries')
    op.drop_index(op.f('ix_barathon_expenses_payer_user_id'), table_name='barathon_expenses')
    op.drop_index(op.f('ix_barathon_expenses_barathon_id'), table_name='barathon_expenses')
    op.drop_table('barathon_expenses')
    # ### end Alembic commands ###
