"""replace cancelled status with stopped

Revision ID: b3e954d882eb
Revises: 
Create Date: 2026-04-02 10:06:24.524100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e954d882eb'
down_revision: Union[str, Sequence[str], None] = '9c1d683a48e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_barathons_end_datetime'), 'barathons', ['end_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barathons_end_datetime'), table_name='barathons')
    # ### end Alembic commands ###
