name: CI/CD Pubrush Backend

on:
  push:
    branches:
      - main

jobs:
  # --- PHASE 1 : BUILD & PUSH (Inchangée) ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push de l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: baptistebriziou/pubrush-backend:latest

  # --- PHASE 2 : DEPLOIEMENT SECURISE VIA TUNNEL SSH ---
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout du code (pour récupérer tes fichiers YAML au besoin)
        uses: actions/checkout@v4

      - name: Mettre en place le tunnel SSH
        uses: nschloe/action-cached-ssh@v1 # Outil pour maintenir le tunnel ouvert
        with:
          # On ouvre un pont entre le port 6443 de GitHub et le port 6443 du VPS
          remote: ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          L: 6443:localhost:6443

      - name: Configuration de kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          # On utilise ton KUBECONFIG_DATA. Comme le tunnel simule un "localhost",
          # GitHub va réussir à communiquer avec le cluster sans que le port soit ouvert sur le web !
          kubeconfig: ${{ secrets.KUBECONFIG_DATA }}

      - name: Relancer le déploiement sur K3s
        run: |
          kubectl rollout restart deployment/pubrush-backend
